name: Build Snapshot 
description: Build (Snapshot) with Maven
inputs:
  jdk_version:  # id of input
    description: Version of JDK to be installed
    required: true
    default: '14'
  maven_version:
    description: Version of Maven to be installed
    required: true
    default: '3.6.3'

runs:
  using: "composite"
  steps:
    - name: Building Snapshot with Maven
      shell: bash
      run: | 
            mvn --version
            mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress --settings ${settings.config.build.tool.settingsPath} ${flags}
