name: Maven CI

on: push

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: buildSnapshot
      run: mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress

    - name: Configure Git user
      run: |
        git config user.email "abinstephen@gmail.com"
        git config user.name "abinstephen"
    
    - name: buildRelease
      run: mvn clean release:clean release:prepare release:perform -Dmaven.test.skip=true --batch-mode --update-snapshots --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
