name: Maven Release

on: workflow_dispatch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Configure Git user
      run: |
        git config user.email "abinstephen@gmail.com"
        git config user.name "abinstephen"
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
       repositories: >
        [
            {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                    "enabled": "true",
                    "updatePolicy": "always",
                    "checksumPolicy": "fail"
                },
                "snapshots": {
                    "enabled": "false",
                    "updatePolicy": "always",
                    "checksumPolicy": "fail"
            }
            }
        ]
       output_file: .m2/settings.xml        
            
    #- name: maven-settings-xml-action
    #  uses: whelk-io/maven-settings-xml-action@v20
    #  with:
    #    repositories: '[{ "id": "central", "url": "https://repo1.maven.org/maven2" }]'
    
    - name: buildRelease
      run: mvn -X  clean release:clean release:prepare release:perform -Dmaven.test.skip=true --batch-mode --update-snapshots --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
