name: Maven Snapshots

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: buildSnapshot
      run: mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: mvn test --update-snapshots --no-transfer-progress 
      
    - name: verify
      run: mvn verify --update-snapshots --no-transfer-progress     
      
    #- name: deploy
    #  run: mvn deploy -Dtest.unit.skipTests=true -Dtest.integration.skipTests=true 
  evaluate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: evaluate
      run: mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout     
      
