name: Maven Snapshots

on: push

jobs:
  Build_Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: getbranch
      run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
     

    - name: buildSnapshot
      run: mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress
  
  Run_Unit_Tests:
    runs-on: ubuntu-latest
    needs: [Build_Code]
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: mvn test --update-snapshots --no-transfer-progress 
      
  Run_Functional_Tests:
    runs-on: ubuntu-latest
    needs: [Run_Unit_Tests]
    steps:
    - uses: actions/checkout@v2
    - name: verify
      run: mvn verify --update-snapshots --no-transfer-progress     
      
  Run_deploy:
    runs-on: ubuntu-latest
    needs: [Run_Functional_Tests]
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: mvn deploy --update-snapshots --no-transfer-progress -Dinternal.repo.pw=${{ secrets.PASSWORD_AR }}  --settings /home/runner/work/test_java-project/test_java-project/settings.xml 
      
  Evaluate:
    runs-on: ubuntu-latest
    needs: [Run_deploy]
    steps:
    - uses: actions/checkout@v2      
    - name: evaluate
      run: mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout     
      
