name: Test

on: workflow_dispatch

jobs:
  Build_Code:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: theonlyfaddyinc/devops-standard-library/composite_action/build_tools/setup-jdk-maven@main
      with:
        jdk_version: '14'
        maven_version: '3.8.1'

    - name: buildSnapshot
      run: mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress
