name: Test

on: workflow_dispatch

jobs:
  Build_Code:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: theonlyfaddyinc/devops-standard-library/composite_actions/setup_build_tools/setup-jdk@main
      with:
        jdk_version: '14' 
    - uses: actions/checkout@v2 
    - uses: theonlyfaddyinc/devops-standard-library/composite_actions/setup_build_tools/setup-maven@main
      with:
         maven-version: '3.6.3'        
    - uses: actions/checkout@v3
      with:
          repository: theonlyfaddyinc/global_configs
          ref: main
          path: ${{ github.workspace }}/global_configs
          
    - uses: ./composite_action/buildSnapshot
      with:
        flags: 'hello'

